# Generated by Django 5.2.4 on 2025-07-27 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0003_customuser_date_of_birth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_view', 'can_view'), ('can_create', 'can_create'), ('can_delete', 'can_delete')]},
        ),
    ]
