# Generated by Django 5.2.4 on 2025-07-22 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0004_alter_userprofile_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'permissions': [('can_add_book', 'can_add_book'), ('can_change_book', 'can_change_book'), ('can_delete_book', 'can_delete_book')]},
        ),
    ]
